name = "Enigma"
uuid = "68071ed3-b3ed-4442-ae89-ae359c4518d1"
authors = ["Ole KrÃ¶ger <o.kroeger@opensourc.es>"]
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
